name: Birthday Email Bot

on:
  schedule:
    - cron: "0 20 * * *"

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install pandas

      - name: Run Python script
        working-directory: "./Python Intermediate/Day 32/Birthday-Wishes-Project"
        run: python main.py
