name: TSLA Stock Alert Bot

on:
  schedule:
  - cron: '30 18 * * *'

  workflow_dispatch:

jobs:
  run-stock-bot:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
    
      - name: Install dependencies
        run: pip install -r "Python Intermediate/Day 36/requirements.txt"
    
      - name: Run stock alert bot
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    
        run: python "Python Intermediate/Day 36/main.py"
